name: Continuous Deployment

on: 
  push:
    branches:
      - test3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
            node-version: 14.x
      - run: npm ci
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    needs: build
    steps:
      - name: Check Directory File
        run: |
          ls -al
      
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "/home/runner/work/cicd-frontend-test/cicd-frontend-test/build/*"
          target: "/var/www/html"
