name: Continuous Deployment

on: 
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy staging
      if: github.ref == 'refs/heads/develop'
      uses: appleboy/ssh-action@master
      with:
        source: "."
        target: "/home/ksp-react"
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al