name: Continuous Deployment

on: 
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Copy repository contents via scp
      if: github.ref == 'refs/heads/develop'
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
      with:
        source: "."
        target: "/home/ksp-frontend-test"

    - name: Deployment
      if: github.ref == 'refs/heads/develop'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        script: |
          cd /home/ksp-frontend-test 
          npm install
          npm run build
          cp -r /home/ksp-frontend-test/build/. /var/www/html
