name: Continuous Deployment

on: 
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy staging
      if: github.ref == 'refs/heads/develop'
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/home/ksp-react"
        script: |
          npm install
          npm run build
          rm -rfv /var/www/html
          mv /home/ksp-react /var/www/html